#!/bin/sh

do_make () {
	./configure $*
	make clean > /dev/null
	make -j8 all > /dev/null
}

mv config.h good-config.h

echo "Disable shell"
do_make --disable-shell

echo "Enable undo"
do_make --enable-undo

echo "Stock make"
do_make

mv good-config.h config.h
