#!/bin/sh

echo "Running sparse..."
sparse -D__linux__ *.[ch]

echo "Running checkpatch..."
for f in *.[ch] X/*.[ch]; do
    [ $f = typedefs.h ] && continue
    checkpatch --file $f | fgrep -q "no obvious style problems" || echo "$f"
done
