/****************************************************************************
 *																			*
 *				 The software found in this file is the						*
 *					  Copyright of Sean MacLennan							*
 *						  All rights reserved.								*
 *																			*
 ****************************************************************************/
struct cnames Cnames[] =
{
	{"Abort",						ZABORT,			H_MISC},
	{"Again",						ZAGAIN,			H_SEARCH},
	{"Append Kill",					ZMAKEDEL,		H_DELETE},
	{"Beginning of Buffer",			ZTOSTART,		H_CURSOR},
	{"Beginning of Line",			ZBEGLINE,		H_CURSOR},
	{"Beginning of Window",			ZBEGWIND,		H_CURSOR},
	{"Bind",						ZBIND,			H_BIND},
	{"Bound To",					ZCMDBIND,		H_BIND},
	{"C Beautify",					ZBEAUTY,		H_SHELL},
	{"C Indent",					ZCINDENT,		H_MODE},
	{"C Insert",					ZCINSERT,		H_NONE},
	{"C-X",							ZCTRLX,			H_NONE},
	{"Calculator",					ZCALC,			H_HELP},
	{"Capitalize Word",				ZCAPWORD,		H_DISP},
	{"Center Line",					ZCENTER,		H_DISP},
	{"Cmd to Buffer",				ZCMDTOBUFF,		H_SHELL},
	{"Cmd to Screen",				ZCMD,			H_SHELL},
	{"Copy Region",					ZCOPYRGN,		H_DELETE},
	{"Copy Word",					ZGETBWORD,		H_DELETE},
	{"Count",						ZCOUNT,			H_HELP},
	{"CWD",							ZCWD,			H_MISC},
	{"Date",						ZDATE,			H_HELP},
	{"Delete Blanks",				ZDELBLANKS,		H_DELETE},
	{"Delete Buffer",				ZKILLBUFF,		H_BUFF},
	{"Delete Character",			ZDELCHAR,		H_DELETE},
	{"Delete Line",					ZDELLINE,		H_DELETE},
	{"Delete Previous Character",	ZRDELCHAR,		H_DELETE},
	{"Delete Previous Word",		ZRDELWORD,		H_DELETE},
	{"Delete Region",				ZDELRGN,		H_DELETE},
	{"Delete to End of Line",		ZDELEOL,		H_DELETE},
	{"Delete Window",				ZDELWIND,		H_BUFF},
	{"Delete Word",					ZDELWORD,		H_DELETE},
	{"Display Bindings",			ZDISPBINDS,		H_BIND},
	{"Empty Buffer",				ZEMPTY,			H_BUFF},
	{"End of Buffer",				ZTOEND,			H_CURSOR},
	{"End of Line",					ZENDLINE,		H_CURSOR},
	{"End of Window",				ZENDWIND,		H_CURSOR},
	{"Exit",						ZEXIT,			H_MISC},
	{"Expression Replace",			ZREREPLACE,		H_SEARCH},
	{"Expression Search",			ZRESRCH,		H_SEARCH},
	{"Extended Command",			ZMETAX,			H_MISC},
	{"Fill Check",					ZFILLCHK,		H_NONE},
	{"Fill Paragraph",				ZFILLPARA,		H_MODE},
	{"Find File",					ZFINDFILE,		H_FILE},
	{"Find Tag",					ZFINDTAG,		H_FILE},
	{"Form Tab",					ZFORMTAB,		H_MODE},
	{"Global RE Search",			ZGRESRCH,		H_SEARCH},
	{"Global Search",				ZGSEARCH,		H_SEARCH},
	{"Goto Line",					ZLGOTO,			H_CURSOR},
	{"Grep",						ZGREP,			H_SHELL},
	{"Grow Window",					ZGROWWINDOW,	H_BUFF},
	{"Help",						ZHELP,			H_HELP},
	{"Hex Output",					ZHEXOUT,		H_HELP},
	{"Incremental Search",			ZINCSRCH,		H_SEARCH},
	{"Indent",						ZINDENT,		H_DISP},
	{"Insert Character",			ZINSERT,		H_NONE},
	{"Insert Space",				ZISPACE,		H_DISP},
	{"Insert/Overwrite",			ZOVERIN,		H_MODE},
	{"Join",						ZJOIN,			H_DELETE},
	{"Key Binding",					ZKEYBIND,		H_BIND},
	{"Kill",						ZKILL,			H_SHELL},
	{"List Buffers",				ZLSTBUFF,		H_BUFF},
	{"Lowercase Region",			ZLOWREGION,		H_DISP},
	{"Lowercase Word",				ZLOWWORD,		H_DISP},
	{"Mail",						ZMAIL,			H_SHELL},
	{"Make",						ZMAKE,			H_SHELL},
	{"Man",							ZMAN,			H_SHELL},
	{"Mark Paragraph",				ZMRKPARA,		H_DELETE},
	{"Meta",						ZMETA,			H_NONE},
	{"Mode",						ZMODE,			H_MODE},
	{"Newline",						ZNEWLINE,		H_NONE},
	{"Next Bookmark",				ZNXTBOOKMRK,	H_CURSOR},
	{"Next Buffer",					ZNEXTBUFF,		H_BUFF},
	{"Next Character",				ZNEXTCHAR,		H_CURSOR},
	{"Next Error",					ZNEXTERR,		H_SHELL},
	{"Next Line",					ZNEXTLINE,		H_CURSOR},
	{"Next Page",					ZNEXTPAGE,		H_CURSOR},
	{"Next Paragraph",				ZFPARA,			H_CURSOR},
	{"Next Window",					ZNEXTWIND,		H_DISP},
	{"Next Word",					ZFWORD,			H_CURSOR},
	{"NULL",						ZNOTIMPL,		H_BIND},
	{"One Window",					Z1WIND,			H_BUFF},
	{"Open Line",					ZOPENLINE,		H_DISP},
	{"Other Next Page",				ZNXTOTHRWIND,	H_BUFF},
	{"Other Previous Page",			ZPREVOTHRWIND,	H_BUFF},
	{"Out To",						ZCGOTO,			H_CURSOR},
	{"Overwrite File",				ZEDITFILE,		H_FILE},
	{"Position",					ZPRINTPOS,		H_HELP},
	{"Previous Character",			ZPREVCHAR,		H_CURSOR},
	{"Previous Line",				ZPREVLINE,		H_CURSOR},
	{"Previous Page",				ZPREVPAGE,		H_CURSOR},
	{"Previous Paragraph",			ZBPARA,			H_CURSOR},
	{"Previous Window",				ZPREVWIND,		H_DISP},
	{"Previous Word",				ZBWORD,			H_CURSOR},
	{"Print",						ZPRINT,			H_SHELL},
	{"Query Replace",				ZQUERY,			H_SEARCH},
	{"Quit",						ZQUIT,			H_MISC},
	{"Quote",						ZQUOTE,			H_MISC},
	{"Read File",					ZFILEREAD,		H_FILE},
	{"Redisplay",					ZREDISPLAY,		H_DISP},
	{"Reference",					ZREF,			H_FILE},
	{"Replace",						ZREPLACE,		H_SEARCH},
	{"Reverse Inc. Search",			ZRINCSRCH,		H_SEARCH},
	{"Reverse Search",				ZRSEARCH,		H_SEARCH},
	{"Save All Files",				ZSAVEALL,		H_FILE},
	{"Save Bindings",				ZSAVEBIND,		H_BIND},
	{"Save Config",					ZSAVECONFIG,	H_HELP},
	{"Save File",					ZFILESAVE,		H_FILE},
	{"Scroll Down",					ZSCROLLDOWN,	H_DISP},
	{"Scroll Up",					ZSCROLLUP,		H_DISP},
	{"Search",						ZSEARCH,		H_SEARCH},
	{"Set Bookmark",				ZSETBOOKMRK,	H_CURSOR},
	{"Set Mark",					ZSETMRK,		H_DELETE},
	{"Set Variable",				ZSETAVAR,		H_HELP},
	{"Setenv",						ZSETENV,		H_MISC},
	{"Shell",						ZSHELL,			H_SHELL},
	{"Shrink Window",				ZSHRINKWIND,	H_BUFF},
	{"Size Window",					ZSIZEWIND,		H_BUFF},
	{"Spell",						ZSPELL,			H_SHELL},
	{"Stats",						ZSTAT,			H_HELP},
	{"Swap Mark and Point",			ZSWAPMRK,		H_CURSOR},
	{"Switch to Buffer",			ZSWITCHTO,		H_BUFF},
	{"Tab",							ZTAB,			H_NONE},
	{"Toggle Case",					ZCASE,			H_SEARCH},
	{"Transpose Characters",		ZSWAPCHAR,		H_DISP},
	{"Transpose Words",				ZSWAPWORD,		H_DISP},
	{"Trim White Space",			ZDELWHITE,		H_DELETE},
	{"Two Windows",					Z2WIND,			H_BUFF},
	{"Undent",						ZUNDENT,		H_DISP},
	{"Undo",				ZUNDO,		H_MISC},
	{"Universal Argument",			ZARG,			H_MISC},
	{"Unmodify",					ZUNMODF,		H_DELETE},
	{"Uppercase Region",			ZUPREGION,		H_DISP},
	{"Uppercase Word",				ZUPWORD,		H_DISP},
	{"View File",					ZVIEWFILE,		H_FILE},
	{"View Line",					ZVIEWLINE,		H_DISP},
	{"Write File",					ZFILEWRITE,		H_FILE},
	{"Yank",						ZYANK,			H_DELETE},
	{"Zoom",						ZZOOM,			H_DISP},
};
