/* Generated by configure Thu Feb 11 21:40:40 EST 2016 */
#define TERMCAP_KEYS 1

#define SPELL 0
#define ZLIB 0
#define SHOW_REGION 1
#define GPM_MOUSE 0
#define UNDO 1
#ifdef __unix__
#define DOPIPES
#endif

/* Don't touch these unless you really know what you are doing. */
#define UNSIGNED_BYTES
#define HAVE_GLOBAL_MARKS
#define HAVE_BUFFER_MARKS
#define HAVE_FREEMARK
#ifdef WIN32
#define BUILTIN_REG
#endif
