/* Generated by configure Sat Sep  3 14:11:00 EDT 2016 */

#define SPELL 0
#define ZLIB 0
#define UNDO 1
#ifdef __unix__
#define DOPIPES
#endif

#define HUGE_FILES 1
#define HUGE_THREADED 1

/* Don't touch these unless you really know what you are doing. */
#define UNSIGNED_BYTES
#define HAVE_GLOBAL_MARKS
#define HAVE_BUFFER_MARKS
#define HAVE_FREEMARK
#ifdef WIN32
#define BUILTIN_REG
#endif
