/* funcs.c - func lists
 * Copyright (C) 1988-2013 Sean MacLennan
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this project; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include "z.h"
#include "cnames.h"

void (*Cmds[][2])() = {
	{ Z1wind,		Znotimpl },
	{ Z2wind,		Znotimpl },
	{ Zabort,		Zabort },
	{ Zagain,		Zpart },
	{ Zarg,			Znotimpl },
	{ Zbeginning_of_line,		Zbeginning_of_line },
	{ Zbpara,		Zbpara },
	{ Zbword,		Zbword },
	{ Zcalc,		Znotimpl },
	{ Zcapitalize_word,	Zcapitalize_word },
	{ Zcase,		Zcase },
	{ Zcenter,		Znotimpl },
	{ Zcopyrgn,		Zcopyrgn },
	{ Zctrlx,		Zctrlx },
	{ Zdelchar,		Zdelchar },
	{ Zdeleol,		Zdeleol },
	{ Zdelline,		Zdelline },
	{ Zdelrgn,		Zdelrgn },
	{ Zdelwhite,		Zdelwhite },
	{ Zdelword,		Zdelword },
	{ Zend_of_line,		Zend_of_line },
	{ Zexit,		Znotimpl },
	{ Zsave_and_exit,	Znotimpl },
	{ Zfileread,		Znotimpl },
	{ Zfilesave,		Znotimpl },
	{ Zfilewrite,		Znotimpl },
	{ Zmode,		Znotimpl },
	{ Zfillpara,		Znotimpl },
	{ Zfindfile,		Znotimpl },
	{ Zfindtag,		Znotimpl },
	{ Zfpara,		Zfpara },
	{ Zfword,		Zfword },
	{ Zgetbword,		Zgetbword },
	{ Zgrowwind,		Znotimpl },
	{ Zhexout,		Znotimpl },
	{ Zinsert,		pinsert },
	{ Zkillbuff,		Znotimpl },
	{ Zlife,		Znotimpl },
	{ Zlgoto,		Znotimpl },
	{ Zlowercase_word,	Zlowercase_word },
	{ Zlstbuff,		Znotimpl },
	{ Zappend_kill,		Zappend_kill },
	{ Zmeta,		Zmeta },
	{ Znextchar,		Znextchar },
	{ Znextline,		Znextline },
	{ Znextpage,		Znotimpl },
	{ Znotimpl,		Znotimpl },
	{ Znxtbookmrk,		Znotimpl },
	{ Znxtothrwind,		Znotimpl },
	{ Zopenline,		Znotimpl },
	{ Zoverin,		Zoverin },
	{ Zprevchar,		Zprevchar },
	{ Zprevline,		Zprevline },
	{ Zprevothrwind,	Znotimpl },
	{ Zprevpage,		Znotimpl },
	{ Zprintpos,		Znotimpl },
	{ Zquery,		Znotimpl },
	{ Zquote,		Zquote },
	{ Zrdelchar,		Zrdelchar },
	{ Zrdelword,		Zrdelword },
	{ Zrereplace,		Znotimpl },
	{ Zresrch,		Znotimpl },
	{ Zrsearch,		Znotimpl },
	{ Zsearch,		Znotimpl },
	{ Zsetavar,		Znotimpl },
	{ Zsetbookmrk,		Znotimpl },
	{ Zsetmrk,		Zsetmrk },
	{ Zshell,		Znotimpl },
	{ Zswap_chars,		Zswap_chars },
	{ Zswap_mark,		Zswap_mark },
	{ Znextwind,		Znotimpl },
	{ Zswap_words,		Zswap_words },
	{ Zswitchto,		Znotimpl },
	{ Ztab,			pinsert },
	{ Ztoend,		Ztoend },
	{ Zbeginning_of_buffer,	Zbeginning_of_buffer },
	{ Zuppercase_word,	Zuppercase_word },
	{ Zyank,		Zyank },
	{ Zc_indent,		pnewline },
	{ Zc_insert,		pinsert },
	{ Zfillchk,		Zfillchk },
	{ Znewline,		pnewline },
	{ Zredisplay,		Znotimpl },
	{ Zmetax,		Znotimpl },
	{ Zbind,		Znotimpl },
	{ Zsavebind,		Znotimpl },
	{ Zdispbinds,		Znotimpl },
	{ Znextbuff,		Znotimpl },
	{ Zkeybind,		Znotimpl },
	{ Zcount,		Znotimpl },
	{ Zincsrch,		Znotimpl },
	{ Zrincsrch,		Znotimpl },
	{ Zunmodf,		Znotimpl },
	{ Zdelblanks,		Znotimpl },
	{ Zmrkpara,		Znotimpl },
	{ Zupregion,		Zupregion },
	{ Zlowregion,		Zlowregion },
	{ Zviewline,		Znotimpl },
	{ Zcmd,			Znotimpl },
	{ Zjoin,		Znotimpl },
	{ Zcgoto,		Znotimpl },
	{ Zmake,		Znotimpl },
	{ Znexterr,		Znotimpl },
	{ Zcmdtobuff,		Znotimpl },
	{ Zkill,		Znotimpl },
	{ Zprevwind,		Znotimpl },
	{ Zhelp,		Znotimpl },
	{ Zgsearch,		Znotimpl },
	{ Zindent,		Znotimpl },
	{ Zundent,		Znotimpl },
	{ Zempty,		Zempty },
	{ Zreplace,		Znotimpl },
	{ Zsaveall,		Znotimpl },
	{ Zdelwind,		Znotimpl },
	{ Zshrinkwind,		Znotimpl },
	{ Zsizewind,		Znotimpl },
	{ Zspell,		Znotimpl },
	{ Zrevertfile,		Znotimpl },
	{ Zscrolldown,		Znotimpl },
	{ Zscrollup,		Znotimpl },
	{ Zcwd,			Znotimpl },
	{ Zcmdbind,		Znotimpl },
	{ Zshowconfig,		Znotimpl },
	{ Zsetenv,		Znotimpl },
	{ Zref,			Znotimpl },
	{ Zgresrch,		Znotimpl },
	{ Zgrep,		Znotimpl },
	{ Zundo,		Znotimpl },
	/* only in the PAW you say? pity... */
	{ Znotimpl,		Zfname },
};
int Curcmds;
