/* funcs.c - func lists
 * Copyright (C) 1988-2010 Sean MacLennan
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this project; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include "z.h"

struct cnames Cnames[] = {
	{"Abort",			ZABORT,		H_MISC},
	{"Again",			ZAGAIN,		H_SEARCH},
	{"Append Kill",			ZMAKEDEL,	H_DELETE},
	{"Beginning of Buffer",		ZTOSTART,	H_CURSOR},
	{"Beginning of Line",		ZBEGLINE,	H_CURSOR},
	{"Beginning of Window",		ZBEGWIND,	H_CURSOR},
	{"Bind",			ZBIND,		H_BIND},
	{"Bound To",			ZCMDBIND,	H_BIND},
	{"C Beautify",			ZBEAUTY,	H_SHELL},
	{"C Indent",			ZCINDENT,	H_MODE},
	{"C Insert",			ZCINSERT,	H_NONE},
	{"C-X",				ZCTRLX,		H_NONE},
	{"Calculator",			ZCALC,		H_HELP},
	{"Capitalize Word",		ZCAPWORD,	H_DISP},
	{"Center Line",			ZCENTER,	H_DISP},
	{"Cmd to Buffer",		ZCMDTOBUFF,	H_SHELL},
	{"Cmd to Screen",		ZCMD,		H_SHELL},
	{"Copy Region",			ZCOPYRGN,	H_DELETE},
	{"Copy Word",			ZGETBWORD,	H_DELETE},
	{"Count",			ZCOUNT,		H_HELP},
	{"CWD",				ZCWD,		H_MISC},
	{"Date",			ZDATE,		H_HELP},
	{"Delete Blanks",		ZDELBLANKS,	H_DELETE},
	{"Delete Buffer",		ZKILLBUFF,	H_BUFF},
	{"Delete Character",		ZDELCHAR,	H_DELETE},
	{"Delete Line",			ZDELLINE,	H_DELETE},
	{"Delete Previous Character",	ZRDELCHAR,	H_DELETE},
	{"Delete Previous Word",	ZRDELWORD,	H_DELETE},
	{"Delete Region",		ZDELRGN,	H_DELETE},
	{"Delete to End of Line",	ZDELEOL,	H_DELETE},
	{"Delete Window",		ZDELWIND,	H_BUFF},
	{"Delete Word",			ZDELWORD,	H_DELETE},
	{"Display Bindings",		ZDISPBINDS,	H_BIND},
	{"Empty Buffer",		ZEMPTY,		H_BUFF},
	{"End of Buffer",		ZTOEND,		H_CURSOR},
	{"End of Line",			ZENDLINE,	H_CURSOR},
	{"End of Window",		ZENDWIND,	H_CURSOR},
	{"Exit",			ZEXIT,		H_MISC},
	{"Expression Replace",		ZREREPLACE,	H_SEARCH},
	{"Expression Search",		ZRESRCH,	H_SEARCH},
	{"Extended Command",		ZMETAX,		H_MISC},
	{"Fill Check",			ZFILLCHK,	H_NONE},
	{"Fill Paragraph",		ZFILLPARA,	H_MODE},
	{"Find File",			ZFINDFILE,	H_FILE},
	{"Find Tag",			ZFINDTAG,	H_FILE},
	{"Form Tab",			ZFORMTAB,	H_MODE},
	{"Global RE Search",		ZGRESRCH,	H_SEARCH},
	{"Global Search",		ZGSEARCH,	H_SEARCH},
	{"Goto Line",			ZLGOTO,		H_CURSOR},
	{"Grep",			ZGREP,		H_SHELL},
	{"Grow Window",			ZGROWWINDOW,	H_BUFF},
	{"Help",			ZHELP,		H_HELP},
	{"Hex Output",			ZHEXOUT,	H_HELP},
	{"Incremental Search",		ZINCSRCH,	H_SEARCH},
	{"Indent",			ZINDENT,	H_DISP},
	{"Insert Character",		ZINSERT,	H_NONE},
	{"Insert Space",		ZISPACE,	H_DISP},
	{"Insert/Overwrite",		ZOVERIN,	H_MODE},
	{"Join",			ZJOIN,		H_DELETE},
	{"Key Binding",			ZKEYBIND,	H_BIND},
	{"Kill",			ZKILL,		H_SHELL},
	{"List Buffers",		ZLSTBUFF,	H_BUFF},
	{"Lowercase Region",		ZLOWREGION,	H_DISP},
	{"Lowercase Word",		ZLOWWORD,	H_DISP},
	{"Mail",			ZMAIL,		H_SHELL},
	{"Make",			ZMAKE,		H_SHELL},
	{"Man",				ZMAN,		H_SHELL},
	{"Mark Paragraph",		ZMRKPARA,	H_DELETE},
	{"Meta",			ZMETA,		H_NONE},
	{"Mode",			ZMODE,		H_MODE},
	{"Newline",			ZNEWLINE,	H_NONE},
	{"Next Bookmark",		ZNXTBOOKMRK,	H_CURSOR},
	{"Next Buffer",			ZNEXTBUFF,	H_BUFF},
	{"Next Character",		ZNEXTCHAR,	H_CURSOR},
	{"Next Error",			ZNEXTERR,	H_SHELL},
	{"Next Line",			ZNEXTLINE,	H_CURSOR},
	{"Next Page",			ZNEXTPAGE,	H_CURSOR},
	{"Next Paragraph",		ZFPARA,		H_CURSOR},
	{"Next Window",			ZNEXTWIND,	H_DISP},
	{"Next Word",			ZFWORD,		H_CURSOR},
	{"NULL",			ZNOTIMPL,	H_BIND},
	{"One Window",			Z1WIND,		H_BUFF},
	{"Open Line",			ZOPENLINE,	H_DISP},
	{"Other Next Page",		ZNXTOTHRWIND,	H_BUFF},
	{"Other Previous Page",		ZPREVOTHRWIND,	H_BUFF},
	{"Out To",			ZCGOTO,		H_CURSOR},
	{"Position",			ZPRINTPOS,	H_HELP},
	{"Previous Character",		ZPREVCHAR,	H_CURSOR},
	{"Previous Line",		ZPREVLINE,	H_CURSOR},
	{"Previous Page",		ZPREVPAGE,	H_CURSOR},
	{"Previous Paragraph",		ZBPARA,		H_CURSOR},
	{"Previous Window",		ZPREVWIND,	H_DISP},
	{"Previous Word",		ZBWORD,		H_CURSOR},
	{"Print",			ZPRINT,		H_SHELL},
	{"Query Replace",		ZQUERY,		H_SEARCH},
	{"Quit",			ZQUIT,		H_MISC},
	{"Quote",			ZQUOTE,		H_MISC},
	{"Read File",			ZFILEREAD,	H_FILE},
	{"Redisplay",			ZREDISPLAY,	H_DISP},
	{"Reference",			ZREF,		H_FILE},
	{"Replace",			ZREPLACE,	H_SEARCH},
	{"Reverse Inc. Search",		ZRINCSRCH,	H_SEARCH},
	{"Reverse Search",		ZRSEARCH,	H_SEARCH},
	{"Revert File",			ZREVERTFILE,	H_FILE},
	{"Save All Files",		ZSAVEALL,	H_FILE},
	{"Save Bindings",		ZSAVEBIND,	H_BIND},
	{"Save Config",			ZSAVECONFIG,	H_HELP},
	{"Save File",			ZFILESAVE,	H_FILE},
	{"Scroll Down",			ZSCROLLDOWN,	H_DISP},
	{"Scroll Up",			ZSCROLLUP,	H_DISP},
	{"Search",			ZSEARCH,	H_SEARCH},
	{"Set Bookmark",		ZSETBOOKMRK,	H_CURSOR},
	{"Set Mark",			ZSETMRK,	H_DELETE},
	{"Set Variable",		ZSETAVAR,	H_HELP},
	{"Setenv",			ZSETENV,	H_MISC},
	{"Shell",			ZSHELL,		H_SHELL},
	{"Shrink Window",		ZSHRINKWIND,	H_BUFF},
	{"Size Window",			ZSIZEWIND,	H_BUFF},
	{"Spell",			ZSPELL,		H_SHELL},
	{"Stats",			ZSTAT,		H_HELP},
	{"Swap Mark and Point",		ZSWAPMRK,	H_CURSOR},
	{"Switch to Buffer",		ZSWITCHTO,	H_BUFF},
	{"Tab",				ZTAB,		H_NONE},
	{"Toggle Case",			ZCASE,		H_SEARCH},
	{"Transpose Characters",	ZSWAPCHAR,	H_DISP},
	{"Transpose Words",		ZSWAPWORD,	H_DISP},
	{"Trim White Space",		ZDELWHITE,	H_DELETE},
	{"Two Windows",			Z2WIND,		H_BUFF},
	{"Undent",			ZUNDENT,	H_DISP},
	{"Undo",			ZUNDO,		H_MISC},
	{"Universal Argument",		ZARG,		H_MISC},
	{"Unmodify",			ZUNMODF,	H_DELETE},
	{"Uppercase Region",		ZUPREGION,	H_DISP},
	{"Uppercase Word",		ZUPWORD,	H_DISP},
	{"View File",			ZVIEWFILE,	H_FILE},
	{"View Line",			ZVIEWLINE,	H_DISP},
	{"Write File",			ZFILEWRITE,	H_FILE},
	{"Yank",			ZYANK,		H_DELETE},
	{"Zoom",			ZZOOM,		H_DISP},
};

void (*Cmds[])() = {
	Z1wind,
	Z2wind,
	Zabort,
	Zagain,
	Zarg,
	Zbegline,
	Zbpara,
	Zbword,
	Zcalc,
	Zcapword,
	Zcase,
	Zcenter,
	Zcopyrgn,
	Zctrlx,
	Zdelchar,
	Zdeleol,
	Zdelline,
	Zdelrgn,
	Zdelwhite,
	Zdelword,
	Zendline,
	Zexit,
	Zfileread,
	Zfilesave,
	Zfilewrite,
	Zmode,
	Zfillpara,
	Zfindfile,
	Zfindtag,
	Zfpara,
	Zfword,
	Zgetbword,
	Zgrowwind,
	Zhexout,
	Zinsert,
	Zkillbuff,
	Zlgoto,
	Zlowword,
	Zlstbuff,
	Zmakedel,
	Zmeta,
	Znextchar,
	Znextline,
	Znextpage,
	Znotimpl,
	Znxtbookmrk,
	Znxtothrwind,
	Zquit,
	Zopenline,
	Zoverin,
	Zprevchar,
	Zprevline,
	Zprevothrwind,
	Zprevpage,
	Zprintpos,
	Zquery,
	Zquote,
	Zrdelchar,
	Zrdelword,
	Zrereplace,
	Zresrch,
	Zrsearch,
	Zsearch,
	Zsetavar,
	Zsetbookmrk,
	Zsetmrk,
	Zshell,
	Zstat,
	Zswapchar,
	Zswapmrk,
	Znextwind,
	Zswapword,
	Zswitchto,
	Ztab,
	Ztoend,
	Ztostart,
	Zupword,
	Zyank,
	Zcindent,
	Zcinsert,
	Zfillchk,
	Znewline,
	Zredisplay,
	Zmetax,
	Zbind,
	Zsavebind,
	Zdispbinds,
	Znextbuff,
	Zkeybind,
	Zcount,
	Zincsrch,
	Zrincsrch,
	Zunmodf,
	Zispace,
	Zprint,
	Zdelblanks,
	Zmrkpara,
	Zupregion,
	Zlowregion,
	Zviewline,
	Zcmd,
	Zjoin,
	Zdate,
	Zcgoto,
	Zmake,
	Znexterr,
	Zcmdtobuff,
	Zkill,
	Zprevwind,
	Zbegwind,
	Zendwind,
	Zhelp,
	Zgsearch,
	Zindent,
	Zundent,
	Zempty,
	Zmail,
	Zman,
	Zreplace,
	Zsaveall,
	Zbeauty,
	Zviewfile,
	Zdelwind,
	Zshrinkwind,
	Zsizewind,
	Zspell,
	Zeditfile, /* 150 */
	Zscrolldown,
	Zscrollup,
	Zformtab,
	Zcwd,
	Zcmdbind,
	Zsaveconfig,
	Zsetenv,
	Zref,
	Zzoom,
	Zgresrch,
	Zgrep,
	Zundo,
};

void (*Vcmds[])() = {
	Z1wind,
	Z2wind,
	Zabort,
	Zagain,
	Zarg,
	Zbegline,
	Zbpara,
	Zbword,
	Zcalc,
	Znotimpl,
	Zcase,
	Znotimpl,
	Zcopyrgn,
	Zctrlx,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zendline,
	Zexit,
	Znotimpl,
	Znotimpl,
	Zfilewrite,
	Zmode,
	Znotimpl,
	Zfindfile,
	Zfindtag,
	Zfpara,
	Zfword,
	Zgetbword,
	Zgrowwind,
	Zhexout,
	Znotimpl,
	Zkillbuff,
	Zlgoto,
	Znotimpl,
	Zlstbuff,
	Zmakedel,
	Zmeta,
	Znextchar,
	Znextline,
	Znextpage,
	Znotimpl,
	Znxtbookmrk,
	Znxtothrwind,
	Zquit,
	Znotimpl,
	Znotimpl,
	Zprevchar,
	Zprevline,
	Zprevothrwind,
	Zprevpage,
	Zprintpos,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zresrch,
	Zrsearch,
	Zsearch,
	Zsetavar,
	Zsetbookmrk,
	Zsetmrk,
	Zshell,
	Zstat,
	Znotimpl,
	Zswapmrk,
	Znextwind,
	Znotimpl,
	Zswitchto,
	Znotimpl,
	Ztoend,
	Ztostart,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zredisplay,
	Zmetax,
	Zbind,
	Zsavebind,
	Zdispbinds,
	Znextbuff,
	Zkeybind,
	Zcount,
	Zincsrch,
	Zrincsrch,
	Zunmodf,
	Znotimpl,
	Zprint,
	Znotimpl,
	Zmrkpara,
	Znotimpl,
	Znotimpl,
	Zviewline,
	Zcmd,
	Znotimpl,
	Zdate,
	Zcgoto,
	Zmake,
	Znexterr,
#ifdef PIPESH
	Znotimpl,
	Zkill,
#else
	Zcmdtobuff,
	Znotimpl,
#endif
	Zprevwind,
	Zbegwind,
	Zendwind,
	Zhelp,
	Zgsearch,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zmail,
	Zman,
	Znotimpl,
	Zsaveall,
	Znotimpl,
	Zviewfile,
	Zdelwind,
	Zshrinkwind,
	Zsizewind,
	Znotimpl,
	Zeditfile,	/* 150 */
	Zscrolldown,
	Zscrollup,
	Znotimpl,
	Zcwd,
	Zcmdbind,
	Zsaveconfig,
	Zsetenv,
	Zref,
	Zzoom,
	Zgresrch,
	Zgrep,
	Znotimpl,
};

void (*Pawcmds[])() = {
	Znotimpl,
	Znotimpl,
	Zabort,
	Zpart,			/* redefined for PAW */
	Znotimpl,
	Zbegline,
	Zbpara,
	Zbword,
	Znotimpl,
	Zcapword,
	Zcase,
	Znotimpl,
	Zcopyrgn,
	Zctrlx,
	Zdelchar,
	Zdeleol,
	Zdelline,
	Zdelrgn,
	Zdelwhite,
	Zdelword,
	Zendline,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zfpara,
	Zfword,
	Zgetbword,
	Znotimpl,
	Znotimpl,
	Pinsert,
	Znotimpl,
	Znotimpl,
	Zlowword,
	Znotimpl,
	Zmakedel,
	Zmeta,
	Znextchar,
	Znextline,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zoverin,
	Zprevchar,
	Zprevline,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zquote,
	Zrdelchar,
	Zrdelword,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zsetmrk,
	Znotimpl,
	Znotimpl,
	Zswapchar,
	Zswapmrk,
	Znotimpl,
	Zswapword,
	Znotimpl,
	Pinsert,	/* override Zinsert */
	Ztoend,
	Ztostart,
	Zupword,
	Zyank,
	Pnewline,
	Pinsert,
	Zfillchk,
	Pnewline,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zispace,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zupregion,
	Zlowregion,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zdate,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zempty,
	Zmail,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl, /* 150 */
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zzoom,
	Znotimpl,
	Znotimpl,
	Znotimpl,
	Zfname,			/* only in the PAW you say? pity... */
};

void (**Funcs)() = Cmds;


#if DBG
static int Testit(void (*p1)(), void (*p2)(), int num, char type)
{
	if (p1 != Znotimpl && p2 != Znotimpl && p1 != p2) {
		Dbg("Alignment %c: %d\n", type, num);
		return 1;
	}
	return 0;
}

void Fcheck(void)
{
	int s1, s2, s3, s4;
	int error = 0;

	/* check the TOLOWER macro */
	if (TOLOWER('c') != 'c')
		Error("OLDLOWER set wrong in config.h");

	/* check sizes of various stuff */
	if (sizeof(Byte)  != 1)
		Error("Byte  size wrong!");
	if (sizeof(struct cnames) % sizeof(char *)) {
		++error;
		Dbg("cnames struct size bad: %d\n", sizeof(struct cnames));
	}
	s1 = sizeof(Cnames) / sizeof(struct cnames);
	s2 = sizeof(Cmds) / sizeof(void *);
	s3 = sizeof(Vcmds) / sizeof(void *);
	s4 = sizeof(Pawcmds) / sizeof(void *) - 1;	/* Paw has 1 extra */
	if ((s1 - s2 + s3 - s4) || s1 != NUMFUNCS) {
		++error;
		Dbg("Cnames: %d Cmds: %d Vcmds: %d Pawcmds: %d NUMFUNCS: %d\n",
			 s1, s2, s3, s4, NUMFUNCS);
	}

	/* validate the Cnames array the best we can */
	for (s1 = 1; s1 < NUMFUNCS; ++s1) {
		if (Stricmp(Cnames[s1].name, Cnames[s1 - 1].name) <= 0) {
			++error;
			Dbg("Problem: (%d) %s and %s\n",
			    s1, Cnames[s1 - 1].name, Cnames[s1].name);
		}
		if (strlen(Cnames[s1].name) > (size_t)30) {
			++error;
			Dbg("%s too long\n", Cnames[s1].name);
		}
		if (strncmp(Cnames[s1].name, "Top", 3) == 0) {
			++error;
			Dbg("Zhelp() Top: %s\n", Cnames[s1].name);
		}
		error += Testit(Cmds[s1], Vcmds[s1], s1, 'V');
		if (Pawcmds[s1] != Pinsert && Pawcmds[s1] != Zpart &&
		    Pawcmds[s1] != Pnewline)
			error += Testit(Cmds[s1], Pawcmds[s1], s1, 'P');
	}

	if (error)
		Error("INTERNAL ERRORS: check z.out file");
}
#endif
