/* funcs.h - Zedit function defines
 * Copyright (C) 1988-2013 Sean MacLennan
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this project; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#define Z1WIND		0
#define Z2WIND		(Z1WIND + 1)
#define ZABORT		(Z2WIND + 1)
#define ZAGAIN		(ZABORT + 1)
#define ZARG		(ZAGAIN + 1)
#define ZBEGINNING_OF_LINE	(ZARG + 1)
#define ZBPARA		(ZBEGINNING_OF_LINE + 1)
#define ZPREVIOUS_WORD		(ZBPARA + 1)
#define ZCALC		(ZPREVIOUS_WORD + 1)
#define ZCAPWORD	(ZCALC + 1)
#define ZCASE		(ZCAPWORD + 1)
#define ZCENTER		(ZCASE + 1)
#define ZCOPY_REGION	(ZCENTER + 1)
#define ZCTRL_X		(ZCOPY_REGION + 1)
#define ZDELETE_CHAR	(ZCTRL_X + 1)
#define ZDELETE_TO_EOL		(ZDELETE_CHAR + 1)
#define ZDELETE_LINE	(ZDELETE_TO_EOL + 1)
#define ZDELETE_REGION		(ZDELETE_LINE + 1)
#define ZDELWHITE	(ZDELETE_REGION + 1)
#define ZDELETE_WORD	(ZDELWHITE + 1)
#define ZEND_OF_LINE	(ZDELETE_WORD + 1)
#define ZEXIT		(ZEND_OF_LINE + 1)
#define ZSAVEEXIT	(ZEXIT + 1)
#define ZFILEREAD	(ZSAVEEXIT + 1)
#define ZFILESAVE	(ZFILEREAD + 1)
#define ZFILEWRITE	(ZFILESAVE + 1)
#define ZMODE		(ZFILEWRITE + 1)
#define ZFILLPARA	(ZMODE + 1)
#define ZFINDFILE	(ZFILLPARA + 1)
#define ZFINDTAG	(ZFINDFILE + 1)
#define ZFPARA		(ZFINDTAG + 1)
#define ZNEXT_WORD		(ZFPARA + 1)
#define ZCOPY_WORD	(ZNEXT_WORD + 1)
#define ZGROWWINDOW	(ZCOPY_WORD + 1)
#define ZHEXOUT		(ZGROWWINDOW + 1)
#define ZINSERT		(ZHEXOUT + 1) /* Also used for pinsert */
#define ZKILLBUFF	(ZINSERT + 1)
#define ZLIFE		(ZKILLBUFF + 1)
#define ZGOTO_LINE		(ZLIFE + 1)
#define ZLOWWORD	(ZGOTO_LINE + 1)
#define ZLSTBUFF	(ZLOWWORD + 1)
#define ZAPPEND_KILL	(ZLSTBUFF + 1)
#define ZMETA		(ZAPPEND_KILL + 1)
#define ZNEXT_CHAR	(ZMETA + 1)
#define ZNEXT_LINE	(ZNEXT_CHAR + 1)
#define ZNEXT_PAGE	(ZNEXT_LINE + 1)
#define ZNOTIMPL	(ZNEXT_PAGE + 1)
#define ZNEXT_BOOKMARK	(ZNOTIMPL + 1)
#define ZNXTOTHRWIND	(ZNEXT_BOOKMARK + 1)
#define ZOPEN_LINE	(ZNXTOTHRWIND + 1)
#define ZOVERIN		(ZOPEN_LINE + 1)
#define ZPREVIOUS_CHAR	(ZOVERIN + 1)
#define ZPREVIOUS_LINE	(ZPREVIOUS_CHAR + 1)
#define ZPREVOTHRWIND	(ZPREVIOUS_LINE + 1)
#define ZPREVIOUS_PAGE	(ZPREVOTHRWIND + 1)
#define ZPRINTPOS	(ZPREVIOUS_PAGE + 1)
#define ZQUERY		(ZPRINTPOS + 1)
#define ZQUOTE		(ZQUERY + 1)
#define ZDELETE_PREVIOUS_CHAR	(ZQUOTE + 1)
#define ZDELETE_PREVIOUS_WORD	(ZDELETE_PREVIOUS_CHAR + 1)
#define ZREREPLACE	(ZDELETE_PREVIOUS_WORD + 1)
#define ZRESRCH		(ZREREPLACE + 1)
#define ZRSEARCH	(ZRESRCH + 1)
#define ZSEARCH		(ZRSEARCH + 1)
#define ZSETAVAR	(ZSEARCH + 1)
#define ZSET_BOOKMARK	(ZSETAVAR + 1)
#define ZSETMRK		(ZSET_BOOKMARK + 1)
#define ZSHELL		(ZSETMRK + 1)
#define ZSWAPCHAR	(ZSHELL + 1)
#define ZSWAPMRK	(ZSWAPCHAR + 1)
#define ZNEXTWIND	(ZSWAPMRK + 1)
#define ZSWAPWORD	(ZNEXTWIND + 1)
#define ZSWITCHTO	(ZSWAPWORD + 1)
#define ZTAB		(ZSWITCHTO + 1)
#define ZEND_OF_BUFFER		(ZTAB + 1)
#define ZTO_START	(ZEND_OF_BUFFER + 1)
#define ZUPWORD		(ZTO_START + 1)
#define ZYANK		(ZUPWORD + 1)
#define ZCINDENT	(ZYANK + 1)
#define ZCINSERT	(ZCINDENT + 1)
#define ZFILLCHK	(ZCINSERT + 1)
#define ZNEWLINE	(ZFILLCHK + 1)
#define ZREDISPLAY	(ZNEWLINE + 1)
#define ZMETA_X		(ZREDISPLAY + 1)
#define ZBIND		(ZMETA_X + 1)
#define ZSAVEBIND	(ZBIND + 1)
#define ZDISPBINDS	(ZSAVEBIND + 1)
#define ZNEXTBUFF	(ZDISPBINDS + 1)
#define ZKEYBIND	(ZNEXTBUFF + 1)
#define ZCOUNT		(ZKEYBIND + 1)
#define ZINCSRCH	(ZCOUNT + 1)
#define ZRINCSRCH	(ZINCSRCH + 1)
#define ZUNMODF		(ZRINCSRCH + 1)
#define ZDELETE_BLANKS	(ZUNMODF + 1)
#define ZMRKPARA	(ZDELETE_BLANKS + 1)
#define ZUPREGION	(ZMRKPARA + 1)
#define ZLOWREGION	(ZUPREGION + 1)
#define ZVIEW_LINE	(ZLOWREGION + 1)
#define ZCMD_TO_SCREEN	(ZVIEW_LINE + 1)
#define ZJOIN		(ZCMD_TO_SCREEN + 1)
#define ZOUT_TO		(ZJOIN + 1)
#define ZMAKE		(ZOUT_TO + 1)
#define ZNEXTERR	(ZMAKE + 1)
#define ZCMD_TO_BUFFER	(ZNEXTERR + 1)
#define ZKILL		(ZCMD_TO_BUFFER + 1)
#define ZPREVWIND	(ZKILL + 1)
#define ZHELP		(ZPREVWIND + 1)
#define ZGSEARCH	(ZHELP + 1)
#define ZINDENT		(ZGSEARCH + 1)
#define ZUNDENT		(ZINDENT + 1)
#define ZEMPTY_BUFFER		(ZUNDENT + 1)
#define ZREPLACE	(ZEMPTY_BUFFER + 1)
#define ZSAVEALL	(ZREPLACE + 1)
#define ZDELWIND	(ZSAVEALL + 1)
#define ZSHRINKWIND	(ZDELWIND + 1)
#define ZSIZEWIND	(ZSHRINKWIND + 1)
#define ZSPELL		(ZSIZEWIND + 1)
#define ZREVERTFILE	(ZSPELL + 1)
#define ZSCROLL_DOWN	(ZREVERTFILE + 1)
#define ZSCROLL_UP	(ZSCROLL_DOWN + 1)
#define ZCWD		(ZSCROLL_UP + 1)
#define ZBOUND_TO	(ZCWD + 1)
#define ZSHOWCONFIG	(ZBOUND_TO + 1)
#define ZSETENV		(ZSHOWCONFIG + 1)
#define ZREF		(ZSETENV + 1)
#define ZGRESRCH	(ZREF + 1)
#define ZGREP		(ZGRESRCH + 1)
#define ZUNDO		(ZGREP + 1)
#define NUMFUNCS	(ZUNDO + 1)

/* this is used by the getfname command in the PAW for command completion */
#define ZFNAME		NUMFUNCS
