#!/bin/sh

if which sparse > /dev/null; then
    echo "Running sparse..."
    sparse -D__unix__ -D__linux__ *.c
else
    echo "ERROR: sparse not found"
fi

K=`uname -r`
checkpatch=`readlink -f /lib/modules/${K}/source/scripts/checkpatch.pl`
if [ ! -f "$checkpatch" ]; then
    checkpatch=`readlink -f /lib/modules/${K}/build/scripts/checkpatch.pl`
    if [ ! -f "$checkpatch" ]; then
	echo "ERROR: checkpatch not found"
	exit 1
    fi
fi

check_one() {
    local opts="--no-tree"
    [ -n "$2" ] && opts="$opts --ignore $2"
    $checkpatch $opts --file $1 | fgrep -q "no obvious style problems" ||
	echo "$1"
}

echo "Running checkpatch..."
if [ 1 -eq 1 ]; then
    for f in *.c; do
	check_one $f SPDX_LICENSE_TAG
    done
fi

for f in *.h; do
    case $f in
	buff.h) check_one buff.h SPDX_LICENSE_TAG,COMPLEX_MACRO,MULTISTATEMENT_MACRO_USE_DO_WHILE,LONG_LINE_COMMENT;;
	defconfig.h) ;; # no point
	*)  check_one $f SPDX_LICENSE_TAG;;
    esac
done
