#!/bin/sh

ZSRC=..
CC=cc
CFLAGS=-O
EXE=./zhsort

# So docs/build works
cd `dirname $0`

# parse the arguments
[ x$1 = x-h ] && { echo "usage: $0 [version]"; exit; }

# we need the version for the title page
if [ x$1 = x ]; then
    version=`awk -F\" '/#define VERSION/ { print $2 }' $ZSRC/z.h`
else
    version=$1
fi

make clean all || exit 1

echo "Checking commands..."
$EXE c command.doc >cmd.tmp || { echo "Errors: aborted"; rm -f cmd.tmp; exit; }
echo "Checking variables..."
$EXE v variable.doc >var.tmp || { echo "Errors: aborted"; rm -f var.tmp; exit; }

echo "Updating help.z"
# SAM no top or bottom margins, long lines
echo ".ll 78"	> help.head
echo ".m1 0"	>>help.head
echo ".m2 0"	>>help.head
echo ".m3 0"	>>help.head
echo ".m4 0"	>>help.head
echo ":ZEDIT" | nroff -me help.head cmd.tmp var.tmp - |
   ./zhack >help.z

echo "Create Appendix A"
./doc2html -H "Appendix A: Commands" < cmd.tmp > app-a.html
echo "Create Appendix B"
./doc2html -H "Appendix B: Variables" < var.tmp > app-b.html

rm help.head cmd.tmp var.tmp
