/****************************************************************************
 *																			*
 *				 The software found in this file is the						*
 *					  Copyright of Sean MacLennan							*
 *						  All rights reserved.								*
 *																			*
 ****************************************************************************/
#define Z1WIND				0
#define Z2WIND				1
#define ZABORT				2
#define ZAGAIN				3
#define ZARG				4
#define ZBEGLINE			5
#define ZBPARA				6
#define ZBWORD				7
#define ZCALC				8
#define ZCAPWORD			9
#define ZCASE				10
#define ZCENTER				11
#define ZCOPYRGN			12
#define ZCTRLX				13
#define ZDELCHAR			14
#define ZDELEOL				15
#define ZDELLINE			16
#define ZDELRGN				17
#define ZDELWHITE			18
#define ZDELWORD			19
#define ZENDLINE			20
#define ZEXIT				21
#define ZFILEREAD			22
#define ZFILESAVE			23
#define ZFILEWRITE			24
#define ZMODE				25
#define ZFILLPARA			26
#define ZFINDFILE			27
#define ZFINDTAG			28
#define ZFPARA				29
#define ZFWORD				30
#define ZGETBWORD			31
#define ZGROWWINDOW			32
#define ZHEXOUT				33
#define ZINSERT				34		/* NOTE: also used for Pinsert */
#define ZKILLBUFF			35
#define ZLGOTO				36
#define ZLOWWORD			37
#define ZLSTBUFF			38
#define ZMAKEDEL			39
#define ZMETA				40
#define ZNEXTCHAR			41
#define ZNEXTLINE			42
#define ZNEXTPAGE			43
#define ZNOTIMPL			44
#define ZNXTBOOKMRK			45
#define ZNXTOTHRWIND		46
#define ZQUIT				47
#define ZOPENLINE			48
#define ZOVERIN				49
#define ZPREVCHAR			50
#define ZPREVLINE			51
#define ZPREVOTHRWIND		52
#define ZPREVPAGE			53
#define ZPRINTPOS			54
#define ZQUERY				55
#define ZQUOTE				56
#define ZRDELCHAR			57
#define ZRDELWORD			58
#define ZREREPLACE			59
#define ZRESRCH				60
#define ZRSEARCH			61
#define ZSEARCH				62
#define ZSETAVAR			63
#define ZSETBOOKMRK			64
#define ZSETMRK				65
#define ZSHELL				66
#define ZSTAT				67
#define ZSWAPCHAR			68
#define ZSWAPMRK			69
#define ZNEXTWIND			70
#define ZSWAPWORD			71
#define ZSWITCHTO			72
#define ZTAB				73
#define ZTOEND				74
#define ZTOSTART			75
#define ZUPWORD				76
#define ZYANK				77
#define ZCINDENT			78
#define ZCINSERT			79
#define ZFILLCHK			80
#define ZNEWLINE			81
#define ZREDISPLAY			82
#define ZMETAX				83
#define ZBIND				84
#define ZSAVEBIND			85
#define ZDISPBINDS			86
#define ZNEXTBUFF			87
#define ZKEYBIND			88
#define ZCOUNT				89
#define ZINCSRCH			90
#define ZRINCSRCH			91
#define ZUNMODF				92
#define ZISPACE				93
#define ZPRINT				94
#define ZDELBLANKS			95
#define ZMRKPARA			96
#define ZUPREGION			97
#define ZLOWREGION			98
#define ZVIEWLINE			99
#define ZSTARTMACRO			100
#define ZENDMACRO			101
#define ZDOMACRO			102
#define ZNAMEMACRO			103
#define ZMACRON				104		/* first macro */
#define ZMACROL				119		/* last  macro */
#define ZREADMACRO			120
#define ZWRITEMACRO			121
#define ZCMD				122
#define ZJOIN				123
#define ZDATE				124
#define ZCGOTO				125
#define ZMAKE				126
#define ZNEXTERR			127
#define ZCMDTOBUFF			128
#define ZKILL				129
#define ZPREVWIND			130
#define ZBEGWIND			131
#define ZENDWIND			132
#define ZHELP				133
#define ZGSEARCH			134
#define ZINDENT				135
#define ZUNDENT				136
#define ZLIFE				137
#define ZEMPTY				138
#define ZMAIL				139
#define ZMAN				140
#define ZREPLACE			141
#define ZSAVEALL			142
#define ZBEAUTY				143
#define ZVIEWFILE			144
#define ZDELWIND			145
#define ZSHRINKWIND			146
#define ZSIZEWIND			147
#define ZSPELL				148
#define ZEDITFILE			149
#define ZSCROLLDOWN			150
#define ZSCROLLUP			151
#define ZCUT				152
#define ZPASTE				153
#define ZFORMTAB			154
#define ZCWD				155
#define ZCMDBIND			156
#define ZSAVECONFIG			157
#define ZSETENV				158
#define ZREF				159
#define ZZOOM				160
#define ZGRESRCH			161
#define ZGREP				162
#define NUMFUNCS			163

/* these are used by the Getfname command in the PAW for command completion */
#define ZFNAME				NUMFUNCS
#define ZMATCH				NUMFUNCS + 1
